#!/bin/bash

# =========================================================================== #
# ============================= < PARAMETROS > ============================== # 
# =========================================================================== #
readonly TCPath=$(dirname $(readlink -f "$0"))
readonly TCLibPath="$TCPath/lib"
readonly TCScripts="$TCPath/scripts"
readonly TCWordlists="$TCPath/wordlists"
readonly TCPayloads="$TCPath/payloads"
readonly TCOutputs="$TCPath/outputs"
readonly TCTmp="/tmp/tc"
TCLang=$(echo $LANG | cut -d "." -f1)

# =========================================================================== #
# =========================== < Incluindo Libs > ============================ # 
# =========================================================================== #
source "$TCLibPath/Format.sh"
source "$TCScripts/WebRecon.sh"
source "$TCScripts/dependencias.sh"
source "$TCLibPath/Ajuda.sh"
source "$TCScripts/Funcoes.sh"


# =========================================================================== #
# =========================== < Opcoes default > ============================ # 
# =========================================================================== #
wlsubdominio="$TCWordlists/subdominios.txt"
wldiretorio="$TCWordlists/diretorios.txt"
# =========================================================================== #
# ======================== < Checando Permissoes > ========================== # 
# =========================================================================== #
usr=$(whoami)

if [ $usr != "root" ]
then
        echo -e "${vermbold}\n\n[-] Necessario privilegio de root para rodar.\n\n${normal}"
        exit
fi

if [ "$1" == "-d" ]
then
	dependencias
	exit
fi
if [ "$1" == "-h" ]
then
	tc_ajuda
	exit
fi

# =========================================================================== #
# ======================== < Iniciando Processos > ========================== # 
# =========================================================================== #

tc_banner

# =========================================================================== #
# ===================== < Verificando dependencias > ======================== # 
# =========================================================================== #

centralizado "git: https://github.com/lokisuite/TwinCrows.git\n"
centralizado "${vermelho}v 1.3.0\n${normal}"
mkdir -p /tmp/tc 2> /dev/null

echo -e "\n\n${cinza}TwinCrows e uma suite de ferramentas de reconhecimento e enumeracao que auxilia na obtencao de informacoes de alvos. A suite permite reconhecimento desde infra a tecnologias e servicos operantes reunindo varias abordagens diferentes.\nEnjoy!!${normal}\n"

dependencias() {
	local dep=()
	for lin in $(cat $TCLibPath/dependencias)
	do
		if [ "$lin" == "postgresql" ]
		then
			ins=$(dpkg --get-selections | grep postgresql | wc -l)
			if [ "$ins" == 0 ]
			then
				echo -e "${vermbold}[-] $lin nao instalado.${normal}"
				dep+=($lin)
			fi
		elif [ "$lin" == "metasploit-framework" ]
		then
			ins=$(builtin type -p msfconsole | wc -l)
			if [ "$ins" == 0 ]
			then
				echo -e "${vermbold}[-] $lin nao instalado.${normal}"
				dep+=($çin)
			fi
		else
			ins=$(builtin type -p $lin | wc -l)
			if [ "$ins" == 0 ]
			then
				echo -e "${vermbold}[-] $lin nao instalado.${normal}"
				dep+=($lin)
			fi
		fi
	done
	sleep 0.05
	if [ ! -z "$dep" ]
	then
		echo -e "\n${vermbold}Existem pacotes a serem instalados."
		echo -e "Para prosseguir, execute ${verdebold} $0 -d ${normal}\n\n"
		exit
	fi
	centralizado "${azulbold}[+] Todas as dependencias ja estao instaladas.${normal}"
	echo -e "\n"
}

dependencias



# =========================================================================== #
# ================================ < Menu > ================================= # 
# =========================================================================== #
trap sair EXIT


nvl1="${vermbold}┌─[${azulbold}Twin${normalbold}\xE2\x98\xA0${azulbold}Crows${vermbold}]\n└─────►${normal}"

while :
do

	echo
	echo -e "${verde}"
	echo -e "01 - HTML Parsing                     08 - Pagesearch"
	echo -e "02 - whois                            09 - PingSweep"
	echo -e "03 - Mapeamento de dominio            10 - Wordlists Work"
	echo -e "04 - Bruteforce de subdominios        11 - Analise de metadados"
	echo -e "05 - Pesquisa de DNS reverso          12 - Enumeration"
	echo -e "06 - Dirsearch                        13 - Payloads msfvenom"
	echo -e "07 - Whatweb"
	echo
	echo -e "0 - sair${normal}"

	echo -e "${normalbold}"
	printf $nvl1
	read  -p ' ' opcao

	echo

	case $opcao in

# =========================================================================== #
# =========================== < HTML Parsing > ============================== #
# =========================================================================== #
	1|01)
		tc_html_parsing $0
	;;
# =========================================================================== #
# =============================== < Whois > ================================= #
# =========================================================================== #
	2|02)
		tc_whois $0
	;;
# =========================================================================== #
# ====================== < Mapeamento de dominio > ========================== #
# =========================================================================== #
	3|03) 
		tc_map_dom $0
	;;
# =========================================================================== #
# ==================== < Bruteforce de subdominio > ========================= #
# =========================================================================== #
	4|04)
		tc_bf_subd $0 $wlsubdominio
	;;
# =========================================================================== #
# =========================== < DNS reverso > =============================== #
# =========================================================================== #
	5|05)
		tc_dns_rev $0
	;;
# =========================================================================== #
# ============================ < Dirsearch > ================================ #
# =========================================================================== #
	6|06)
		tc_dirsearch $0 $wldiretorio
	;;
# =========================================================================== #
# ============================= < Whatweb > ================================= #
# =========================================================================== #
	7|07)
		tc_whatweb $0
	;;
# =========================================================================== #
# =========================== < Pagesearch > ================================ #
# =========================================================================== #
	8|08)
		tc_pagesearch $0
	;;
# =========================================================================== #
# ============================ < PingSweep > ================================ #
# =========================================================================== #
	9|09)
		tc_pingsweep $0
	;;
# =========================================================================== #
# ========================= < Mutacao de wordlist > ========================= #
# =========================================================================== #
	10)
		nvl2="${vermbold}┌─[${azulbold}Twin${normalbold}\xE2\x98\xA0${azulbold}Crows${vermbold}]──[${azulbold}Wordlists${vermbold}]\n└─────►${normal}"
		tc_wl_wk $0
	;;
# =========================================================================== #
# ================== < Analise de metadados de arquivos > =================== #
# =========================================================================== #
        11)
                tc_metadados $0
        ;;
# =========================================================================== #
# ================== < Analise de metadados de arquivos > =================== #
# =========================================================================== #
        12)
		nvl2="${vermbold}┌─[${azulbold}Twin${normalbold}\xE2\x98\xA0${azulbold}Crows${vermbold}]──[${azulbold}Enumeration${vermbold}]\n└─────►${normal}"
                tc_enumeration $0
        ;;
# =========================================================================== #
# ============================ < Payloads > ================================= #
# =========================================================================== #
        13)
		nvl2="${vermbold}┌─[${azulbold}Twin${normalbold}\xE2\x98\xA0${azulbold}Crows${vermbold}]──[${azulbold}Payloads${vermbold}]\n└─────►${normal}"
                tc_payload $0
        ;;
# =========================================================================== #
# ============================== < Nmap utils > ============================= #
# =========================================================================== #
	14)
		centralizado "${azulbold}===== Nmap utils =====\n\n${normal}"
		echo -e "${cinza}Este modulo traz algumas opcoes pre configuradas de utilizacao do nmap, como o nmap e uma ferramenta extremamente completa, estes modulos sao so uma fracao de sua capacidade."
		echo
		echo -e "Escolha uma opcao:"
		echo
		echo -e "${verde}1 - Descobrir hosts ativos na rede"
                echo "2 - Escaneamento de portas padrao"
                echo "3 - Escaneamento -sS por portas"
                echo -e "4 - Scan com evasion de firewall/IDS${normalbold}"
                echo
		read -n2 -p '>> ' resp3
                echo
                case $resp3 in
                        "1")
                                echo -e "${verde}Informe o IP do host com intervalo ex(192.168.0-255 ou 192.168.0/24):${normalbold}"
                                read -p '>> ' dominio
                                echo 
                                echo
				echo -e "${verde}Caso queira salvar um arquivo de saida, por favor informar:${normalbold}"
				read -p '>> ' arquivo
                                centralizado "${azulbold}===== RESULTADO =====${normal}\n"
                                echo
                                echo
                                nmap_host $dominio $arquivo
                                echo
                                echo
                                exit
                        ;;
			"2")
				echo -e "${verde}Informe o IP do host:${normalbold}"
				read -p '>> ' ip
				echo -e "\n\n"
				echo -e "${verde}Caso queira salvar um arquivo de saida, por favor informar:${normalbold}"
                                read -p '>> ' arquivo
                                centralizado "${azulbold}===== RESULTADO =====${normal}\n"
                                echo
                                echo
				nmap_padrao $ip $arquivo
				echo -e "\n\n"
				exit
			;;
			"3")
				echo -e "${verde}Deseja carregar um arquivo de hosts? [s/n].${normalbold}"
				read -p '>> ' opcao
				echo -e "\n\n"
				if [ "$opcao" == "s" ]
				then
					echo -e "${verde}Informe o caminho para o arquivo:${normalbold}"
					read -p '>> ' origem
				else
					echo -e "${verde}Informe o IP do host:${normalbold}"
        	                        read -p '>> ' ip
				fi
                                echo -e "\n\n"
				echo -e "${verde}Informe as portas ex(21,22,25 ou 0-80):${normalbold}"
				read -p '>> ' porta
				echo -e '\n\n'
                                echo -e "${verde}Caso queira salvar um arquivo de saida, por fafor informe ${normalbold}"
                                read -p '>> ' arquivo
				centralizado "${azulbold}===== RESULTADO =====${normal}\n"
				echo -e '\n\n'
				if [ ! -z "$origem" ]
				then
					modo="-iL=$origem"
				else
					modo="$ip"
				fi
				nmap_portas $modo $porta $arquivo
				echo -e "\n\n"
				exit
			;;
			"4")
				echo -e "${verde}Informe o IP do host:${normalbold}"
				read -p '>> ' ip
				echo -e "\n"
				echo -e "${verde}Informe a porta para bypass:${normalbold}"
				read -p '>> ' portabp
				echo -e "\n"
				echo -e "${verde}Informe a quantidade de IPs falsos:${normalbold}"
				read -p '>> ' decoy
				echo -e "\n"
				echo -e "${verde}Informe as portas ex(21,22,25 ou 0-80):${normalbold}"
				read -p '>> ' porta
				echo -e "\n"
				echo -e "${verde}Caso queira salvar um arquivo de saida, por favor informe:${normalbold}"
				read -p '>> ' arquivo
				echo
				nmap_firewall $ip $portabp $decoy $porta $arquivo
				exit
			;;
		esac


	;;
# =========================================================================== #
# ================================ < Sair > ================================= #
# =========================================================================== #
	0)
		sair
	;;
# =========================================================================== #
# =========================== < Opcao invalida > ============================ #
# =========================================================================== #
	*)
		echo -e "${vermbold}OPÇÃO INVÁLIDA!!\n\n"
	;;



	esac
done

